name = "halcyon"
description = "Clean and simple personal site/blog theme"
license = "MIT"
homepage = "https://github.com/m0ddr/halcyon"
min_version = "0.1.0"

[author]
name = "M0ddr"
homepage = "https://github.com/m0ddr"